version: '3'
services:
  influxdb:
    image: influxdb:2.0.9
    container_name: influxdb
    user: '1000'
    ports:
      - '8086:8086'
    volumes:
      - /media/pi/BEBA-26C3:/var/lib/influxdb2:rw
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=org
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket
      - DOCKER_INFLUXDB_INIT_RETENTION=104w
    restart: always

  grafana:
    image: grafana/grafana:8.2.2
    container_name: grafana
    user: '1000'
    ports:
      - '3000:3000'
    volumes:
      - /media/pi/BEBA-26C3:/var/lib/grafana:rw
    depends_on:
      - influxdb
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_INSTALL_PLUGINS=innius-video-panel
    restart: always
